### ISSUE TITLE
Comparing models for hyperparameter optimization

### ISSUE THREAD

**Issue by esafak** [david-cortes/hpfrec#1]
I tried to optimize the number of components by using a proper train/test split with `fit(val_set)` and running `eval_llk` at the end, however I got `'input_df' has no combinations of users and itemsin common with the training set.` regardless of whether I ran `eval_llk` on the training/test/complete data set.

**Comment by david-cortes** [comment]
Thanks for reporting the problem! Please be aware that the data frames might be modified in-place. Could you take the head of the training dataframe before and after fitting the model (e.g. `train.head()`)? If it looks exactly the same before and after, could you write here the parameters that you passed to the constructor call? (i.e. how did you call `HFPF(<parameters you put here>)`)

**Comment by esafak** [comment]
`train.head()` looks the same, and I tried recreating `train` to avoid that problem, to no avail. I call HPF with `rec = HPF(k=foo)`.

**Comment by david-cortes** [comment]
Oops yeah that's broken, I'll fix it later today. Sorry.

**Comment by david-cortes** [comment]
Please try again now (change was also pushed to pypi)

**Comment by esafak** [comment]
I can now run `eval_llk(train)` but not `eval_llk(test)`, and the former returns a LLK that does not match the "Final log-likelihood". Please can you persist the final LLK in the HPF object after running fit()?

**Comment by david-cortes** [comment]
Does `eval_llk(test)` throw the same error or something else? If the same error, can you check it has the same `dtypes` as `train`? If some other error, can you try `eval_llk(test, full_llk=False)`?

If you run `predict(test.UserId, test.ItemId)`, does it throw you NA values or perhaps some error?

The mismatch however is intentional: the numbers you get while running `fit` are calculated also for all missing entries in the data, e.g. if you have 5 items and a user has data for 3 of them, it will also calculate the likelihood for the other two, assuming they have a count of zero; while the `eval_llk` function will only calculate it for the entries that you pass to it.

Hadn't thought about storing the final likelihood value, guess that'll be a good addition for a future release.

**Comment by esafak** [comment]
It worked when I ensured that the ItemId column was categorical. This is worth documenting.

**Comment by david-cortes** [comment]
Hmm, that’s a really strange behavior, and it certainly wasn’t expected to work with pandas’ categoricals. I tried the following on my side (python 3.6.5, pandas 0.23.0, running on linux):
* Fit the model to data that had IDs as type categorical, both integer and string IDs, then ran `eval_llk` on data that was either categorical or integer/str – worked fine.
* Fit the model to data that had IDs as integer/strings, then ran `eval_llk` on data that had dtypes `categorical`, also worked fine.

Does the following code run fine for you?
```python
import numpy as np, pandas as pd
from sklearn.model_selection import train_test_split
from hpfrec import HPF

nusers=100
nitems=50
nobs=500
np.random.seed(1)

## categoricals
df = pd.DataFrame({
    'UserId':np.random.randint(nusers, size=nobs),
    'ItemId':np.random.randint(nitems, size=nobs),
    'Count':np.random.uniform(low=1, high=10, size=nobs)
})

df['UserId'] = pd.Categorical(df.UserId.map(lambda x: 's' + str(x)))
df['ItemId'] = pd.Categorical(df.ItemId.map(lambda x: 's' + str(x)))

train, test = train_test_split(a1, test_size=0.3, random_state=2)
test['UserId'] = np.array(test.UserId)
test['ItemId'] = np.array(test.ItemId)

h = HPF(k=10)
h.fit(train)
h.eval_llk(test)

## integers
df = pd.DataFrame({
    'UserId':np.random.randint(nusers, size=nobs),
    'ItemId':np.random.randint(nitems, size=nobs),
    'Count':np.random.uniform(low=1, high=10, size=nobs)
})
train, test = train_test_split(a1, test_size=0.3, random_state=2)
h = HPF(k=10)
h.fit(train)
h.eval_llk(test)
```

Also, were you using categoricals on the train dataframe?

Could you give me information about your setup? (python and pandas version, operating system).

**Comment by esafak** [comment]
It worked when I changed `a1` to `df`. I'm using python 3.6 on OSX. I'll edit this post with more details if I find time.

**Comment by abs51295** [comment]
@esafak can you provide your code to perform hyper-parameter optimization with this library?

**Comment by esafak** [comment]
I looped over different values of the dimensionality and picked the value with the best validation performance. Nothing to share.
