### ISSUE TITLE
Bug - add_user() only works with int ids, our count_df has UserId and ItemId as strings.

### ISSUE THREAD

**Issue by ayunus22198** [david-cortes/hpfrec#10]
Hey David, good job on the code. I'm experiencing a bug with add_user(), hoping you can can take a look with this video.

https://user-images.githubusercontent.com/31936436/117243808-c097e800-adec-11eb-825b-91632f07a909.mp4

**Comment by david-cortes** [comment]
Thanks for the bug report. Unfortunately, the error trace got shortened so it doesn't tell where in this library did it fail. Please copy the full log here (using three backticks before and after for code formatting).

BTW, the ID should be something similar to the IDs in the input data frame, not row numbers.

**Comment by david-cortes** [comment]
I've pushed a small update which should fix the problem, at least with newer versions of numpy. Please try again:
```pip install -U hpfrec```

**Comment by ayunus22198** [comment]
Hey thanks! I will take a look.
