### ISSUE TITLE
Persistent Hanging of hpfrec.HPF().fit() in Production ML Pipeline

### ISSUE THREAD

**Issue by cbrow97** [david-cortes/hpfrec#14]
I'll preface this issue by saying that I know I do not have enough information to provide to expect a solution, but I figured I raise this concern in case anyone else has been troubleshooting a similar problem.

**Context**
Our production ML pipeline that relies on this package has been operational without any issues for the past year. However, starting from July 17th, 2023, the pipeline has been persistently hanging when calling the `hpfrec.HPF().fit()` function, leading to a significant increase in job processing time from 1 hour to over 50 hours (without completion).

**Symptoms**
The verbose messaging displays as follows during the hang:

```
Number of users: 820137
Number of items: 472
Latent factors to use: 50

Initializing parameters...
Allocating Phi matrix...
Initializing optimization procedure...
```

This problem occurs even after ensuring that the data fed into the model hasn't been altered, and is reproduced when rolling back the data to previous dates.

**Environment Details**

Databricks cluster specs:
Driver: r4.8xlarge
Workers: r4.8xlarge
2-8 workers
7.3 LTS (includes Apache Spark 3.0.1, Scala 2.12)
Python 3.7
Located in us-east-1c
Package version: hpfrec==0.2.3.1

**Code Snippet**
Here is the code snippet for initializing and fitting the model:
```
model = hpfrec.HPF(
    k=50,
    full_llk=False,
    random_seed=123,
    check_every=10,
    maxiter=150,
    reindex=True,
    allow_inconsistent_math=True,
    ncores=-1,
    stop_crit="diff-norm",
    verbose=True,
)
model.fit(input_data)
```

We are unsure of the cause of this issue and are eager to troubleshoot this to maintain the efficiency of our production pipeline. Any insights or advice would be highly appreciated.

**Comment by david-cortes** [comment]
Thanks for the bug report.

Since 2023-07-17 is the date cython 3.0.0 was released, I assume the breaking changes there are to blame.

Does your pipeline work if you build an older version of this package (say, `0.2.6`) with an older version of cython? In order to do that, you'll first need to install an older cython alonside with setup-related packages and other dependencies:
```shell
pip install cython==0.29.36 setuptools wheel numpy scipy
```

And then install this package without build isolation:
```shell
pip install --no-use-pep517 --force-reinstall hpfrec hpfrec==0.2.6
```

If that _still_ doesn't work, does the conda-forge version of this package work for you?

**Comment by cbrow97** [comment]
@david-cortes Thank you for the response!

I am currently using version `0.2.3.1` of the `hpfrec` package. I checked the Databricks YAML and the cluster is installing `cython=0.29.15`. I am going to specify the install to `cython==0.29.36` like you suggested. For reference, [here](https://docs.databricks.com/release-notes/runtime/7.3lts-ml.html) are the specs of the cluster I'm running `hpfrec==0.2.3.1` on. 

I'll report back in a few hours.

**Comment by david-cortes** [comment]
> @david-cortes Thank you for the response!
> 
> I am currently using version `0.2.3.1` of the `hpfrec` package. I checked the Databricks YAML and the cluster is installing `cython=0.29.15`. I am going to specify the install to `cython==0.29.36` like you suggested. For reference, [here](https://docs.databricks.com/release-notes/runtime/7.3lts-ml.html) are the specs of the cluster I'm running `hpfrec==0.2.3.1` on.
> 
> I'll report back in a few hours.

To be clear: you'll need that older cython as a _build dependency_, not just as a runtime dependency.

**Comment by cbrow97** [comment]
> > @david-cortes Thank you for the response!
> > I am currently using version `0.2.3.1` of the `hpfrec` package. I checked the Databricks YAML and the cluster is installing `cython=0.29.15`. I am going to specify the install to `cython==0.29.36` like you suggested. For reference, [here](https://docs.databricks.com/release-notes/runtime/7.3lts-ml.html) are the specs of the cluster I'm running `hpfrec==0.2.3.1` on.
> > I'll report back in a few hours.
> 
> To be clear: you'll need that older cython as a _build dependency_, not just as a runtime dependency.

Got it - thanks for the clarification

**Comment by david-cortes** [comment]
I suspect the issue is a bug with cython. I've pushed a newer version that should now again work with older cython, and should stick to that older cython at buildtime unless otherwise specified. Could you give it a try and see if it solves your issue?
```shell
pip install hpfrec==0.2.10
```

**Comment by cbrow97** [comment]
@david-cortes gladly - I'll start another run with `hpfrec==0.2.10` and will report back asap (no later than EOD).

**Comment by cbrow97** [comment]
@david-cortes First, thank you very much for building a version to try to resolve the issues we're seeing. It's greatly appreciated. 

Unfortunately the version you suggested won't work because it requires `numpy>=1.25`. Our job must run on Python 3.7, and `numpy>=1.25` must be installed on Python 3.8 or greater. 

I am still working on building my own version of `hpfrec==0.2.3.1` and specify the cython version. I will build the .whl and install it on the cluster I'm using to test.

**Comment by cbrow97** [comment]
Apologies for the delay. I have not been able to work on this today as much as I had intended.

My first pass of rolling back Cython to building the .whl locally was unsuccessful when trying to run on the job cluster. There are a few more things I'm going to test. I'll reply back by EoD tomorrow and close this issue if I can't resolve or have a specific ask of you.

Thanks again for all the help.

**Comment by cbrow97** [comment]
@david-cortes I'm going to close this. We were unable to successfully fit the model on the legacy [dataricks cluster](https://docs.databricks.com/release-notes/runtime/7.3lts-ml.html) we're running on.

We greatly appreciate the help you provided - take care!
