### ISSUE TITLE
Finding the top items in each topic

### ISSUE THREAD

**Issue by JackMack21** [david-cortes/hpfrec#8]
I am trying to find the top items which appear in each of the $K$ topics. From the documentation I have assumed that I must call 
```
recommender = HPF(k=10, a=0.3, a_prime=0.3, b_prime=1.0,
                 c=0.3, c_prime=0.3, d_prime=1.0, ncores=-1,
                 stop_crit='val-llk', check_every=10, stop_thr=1e-3,
                 maxiter=150, reindex=True, random_seed = 123,
                 allow_inconsistent_math=False, verbose=True, full_llk=False,
                 keep_data=True, save_folder=None, produce_dicts=True)
recommender.fit(train, val_set = validation)

recommender.item_dict
```

however the `recommender.item_dict` outputs:

```
AttributeError                            Traceback (most recent call last)
<ipython-input-24-05d52252689c> in <module>()
----> 1 recommender.item_dict

AttributeError: 'HPF' object has no attribute 'item_dict'
```

Have I missed sometime when I call HPF?

**Comment by david-cortes** [comment]
That's an issue with how the HTML of the docs is rendered. In the docstring, it's referred to as `item_dict_`, but the HTML is showing it as `item_dict` (no underscore at the end). I've now updated the sphinx version used in readthedocs, should be rendering correctly now if you press Ctrl + F5.
