### ISSUE TITLE
Recovering model from save_folder files

### ISSUE THREAD

**Issue by ayunus22198** [david-cortes/hpfrec#9]
Hey David, 

Thank you for the code. We have a fairly large dataset, and I am interested in saving the recommender model to a file so I can avoid training over and over again (we don't want to call recommender.fit() repetitively). We put a google drive path to the save_folder field and are able to see the files. Is there a way we can recover the model using these files?

<img width="292" alt="Screen Shot 2021-05-02 at 5 56 44 PM" src="https://user-images.githubusercontent.com/31936436/116833747-ce8d0500-ab6f-11eb-86b5-1334761cb601.png">

**Comment by david-cortes** [comment]
No, there isn't, those are just text files with the fitted factors. If you need to serialize a model object you can use `dill` or similar.
